### ISSUE TITLE
Pure X11 overlay?

### ISSUE THREAD

**Issue by commonuserlol** [rdbo/imgui-overlay#1]
Hey, as i see, you still using GLFW. Is there any project which uses pure X11 OpenGL? (or smth, no idea).

**Comment by rdbo** [comment]
> Hey, as i see, you still using GLFW. Is there any project which uses pure X11 OpenGL? (or smth, no idea).

I've never even seen another X11 overlay project. But that's definitely doable. You can do it through X11 + GLX. I'd still use this one though, specially since GLFW has support for passthrough windows, which you'd have to implement manually I think.

**Comment by commonuserlol** [comment]
Ok i will try implement it.
> I'd still use this one though

You should know unity engine, so it uses `glXSwapBuffers`, not glfw library. And my goal is inject dear imgui, so variant with glfw wont work

**Comment by rdbo** [comment]
> Ok i will try implement it.
> 
> > I'd still use this one though
> 
> You should know unity engine, so it uses `glXSwapBuffers`, not glfw library. And my goal is inject dear imgui, so variant with glfw wont work

It doesn't matter what Unity uses, it's an overlay. You can use anything that has window passthrough.
If you were hooking Unity's render functions, then yeah, GLFW will be a problem. But that's not the case.

**Comment by commonuserlol** [comment]
You mean overlay like other window instance? If yes this not suits me :(

**Comment by rdbo** [comment]
Yes, this project creates a transparent window on top of the game window that allows you to draw your hack.

> You mean overlay like other window instance? If yes this not suits me :(

**Comment by commonuserlol** [comment]
Nono, i mean like umm this 
![ss](https://github.com/rdbo/imgui-overlay/assets/111648021/77fc7c5e-f69f-4902-9f86-0598d9d892ea)

Sorry, me noob

**Comment by rdbo** [comment]
I don't understand what do you mean.

**Comment by commonuserlol** [comment]
Like, you have opened app, for example firefox. It have window with tabs, etc. And you opened other window of firefox (not tab). So i mean does your overlay creates "fake" instance of app (it will be displayed as second window) or just injects and runs in current app

**Comment by rdbo** [comment]
> Like, you have opened app, for example firefox. It have window with tabs, etc. And you opened other window of firefox (not tab). So i mean does your overlay creates "fake" instance of app (it will be displayed as second window) or just injects and runs in current app

It doesn't start another instance of the app. It just creates another window on top of the app window.
E.g the game is running, you run/inject the overlay, now the overlay is on top of the game window.

**Comment by commonuserlol** [comment]
ok thx. last thing, can you license this under some permissive license?

**Comment by rdbo** [comment]
> ok thx. last thing, can you license this under some permissive license?

Done
